extensions = {
    # --- Images ---
    ".jpg": "Images",
    ".jpeg": "Images",
    ".png": "Images",
    ".apng": "Images",
    ".avif": "Images",
    ".jfif": "Images",
    ".pjpeg": "Images",
    ".pjp": "Images",
    ".gif": "Images",
    ".svg": "Images",
    ".webp": "Images",
    ".bmp": "Images",
    ".tiff": "Images",
    ".tif": "Images",
    ".ico": "Images",
    ".heic": "Images",
    ".eps": "Images",
    # --- Videos ---
    ".mp4": "Videos",
    ".mov": "Videos",
    ".webm": "Videos",
    ".mkv": "Videos",
    ".flv": "Videos",
    ".vob": "Videos",
    ".ogv": "Videos",
    ".avi": "Videos",
    ".wmv": "Videos",
    ".m4v": "Videos",
    ".mpg": "Videos",
    ".mpeg": "Videos",
    ".3gp": "Videos",
    ".3g2": "Videos",
    ".f4v": "Videos",
    ".swf": "Videos",
    # --- Documents ---
    ".pdf": "Documents",
    ".txt": "Documents",
    ".doc": "Documents",
    ".docx": "Documents",
    ".odt": "Documents",
    ".rtf": "Documents",
    ".epub": "Documents",
    ".md": "Documents",
    ".ppt": "Documents",
    ".pptx": "Documents",
    ".xls": "Documents",
    ".xlsx": "Documents",
    ".csv": "Documents",
    ".pages": "Documents",
    ".numbers": "Documents",
    ".key": "Documents",
    # --- Audio ---
    ".mp3": "Audio",
    ".wav": "Audio",
    ".aac": "Audio",
    ".flac": "Audio",
    ".ogg": "Audio",
    ".m4a": "Audio",
    ".wma": "Audio",
    ".aiff": "Audio",
    ".alac": "Audio",
    ".opus": "Audio",
    ".mid": "Audio",
    ".midi": "Audio",
    # --- Archives ---
    ".zip": "Archives",
    ".rar": "Archives",
    ".7z": "Archives",
    ".tar": "Archives",
    ".gz": "Archives",
    ".bz2": "Archives",
    ".iso": "Archives",
    ".dmg": "Archives",
    ".xz": "Archives",
    # --- Data & Config ---
    ".json": "Data",
    ".xml": "Data",
    ".yml": "Data",
    ".yaml": "Data",
    ".sql": "Data",
    ".log": "Data",
    ".ini": "Data",
    ".conf": "Data",
    ".env": "Data",
    # --- Programming ---
    ".py": "Programming",
    ".js": "Programming",
    ".ts": "Programming",
    ".html": "Programming",
    ".css": "Programming",
    ".cpp": "Programming",
    ".c": "Programming",
    ".java": "Programming",
    ".go": "Programming",
    ".rb": "Programming",
    ".php": "Programming",
    ".sh": "Programming",
    # --- Executables ---
    ".exe": "Executables",
    ".msi": "Executables",
    ".apk": "Executables",
    ".app": "Executables",
    ".bat": "Executables",
    # --- Design ---
    ".psd": "Design",
    ".ai": "Design",
    ".xd": "Design",
    ".fig": "Design",
    ".sketch": "Design",
}
